version: "3.8"
services:
  wallet-tracker-frontend:
    image: test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: https://f4f8-2406-7400-43-5d8b-293c-a6ad-72ee-a9b3.ngrok-free.app
    ports:
      - "5002:5002"
    command: >
      sh -c "yarn global add serve && serve -s build"
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
